// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: nest.proto

package nestpb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DepartmentMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Employees        []*EmployeeMessage   `protobuf:"bytes,3,rep,name=employees,proto3" json:"employees,omitempty"`
	ParentDepartment *DepartmentMessage   `protobuf:"bytes,4,opt,name=parent_department,json=parentDepartment,proto3" json:"parent_department,omitempty"`
	ChildDepartments []*DepartmentMessage `protobuf:"bytes,5,rep,name=child_departments,json=childDepartments,proto3" json:"child_departments,omitempty"`
}

func (x *DepartmentMessage) Reset() {
	*x = DepartmentMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepartmentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentMessage) ProtoMessage() {}

func (x *DepartmentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_nest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentMessage.ProtoReflect.Descriptor instead.
func (*DepartmentMessage) Descriptor() ([]byte, []int) {
	return file_nest_proto_rawDescGZIP(), []int{0}
}

func (x *DepartmentMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DepartmentMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DepartmentMessage) GetEmployees() []*EmployeeMessage {
	if x != nil {
		return x.Employees
	}
	return nil
}

func (x *DepartmentMessage) GetParentDepartment() *DepartmentMessage {
	if x != nil {
		return x.ParentDepartment
	}
	return nil
}

func (x *DepartmentMessage) GetChildDepartments() []*DepartmentMessage {
	if x != nil {
		return x.ChildDepartments
	}
	return nil
}

type EmployeeMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *EmployeeMessage) Reset() {
	*x = EmployeeMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nest_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmployeeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeMessage) ProtoMessage() {}

func (x *EmployeeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_nest_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeMessage.ProtoReflect.Descriptor instead.
func (*EmployeeMessage) Descriptor() ([]byte, []int) {
	return file_nest_proto_rawDescGZIP(), []int{1}
}

func (x *EmployeeMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EmployeeMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_nest_proto protoreflect.FileDescriptor

var file_nest_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6e, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6e, 0x65,
	0x73, 0x74, 0x22, 0xf8, 0x01, 0x0a, 0x11, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x33, 0x0a, 0x09,
	0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x6e, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x09, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65,
	0x73, 0x12, 0x44, 0x0a, 0x11, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x64, 0x65, 0x70, 0x61,
	0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6e,
	0x65, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x10, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x70,
	0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x44, 0x0a, 0x11, 0x63, 0x68, 0x69, 0x6c, 0x64,
	0x5f, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6e, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x10, 0x63, 0x68, 0x69,
	0x6c, 0x64, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x35, 0x0a,
	0x0f, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x3b, 0x6e, 0x65, 0x73, 0x74, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nest_proto_rawDescOnce sync.Once
	file_nest_proto_rawDescData = file_nest_proto_rawDesc
)

func file_nest_proto_rawDescGZIP() []byte {
	file_nest_proto_rawDescOnce.Do(func() {
		file_nest_proto_rawDescData = protoimpl.X.CompressGZIP(file_nest_proto_rawDescData)
	})
	return file_nest_proto_rawDescData
}

var file_nest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_nest_proto_goTypes = []interface{}{
	(*DepartmentMessage)(nil), // 0: nest.DepartmentMessage
	(*EmployeeMessage)(nil),   // 1: nest.EmployeeMessage
}
var file_nest_proto_depIdxs = []int32{
	1, // 0: nest.DepartmentMessage.employees:type_name -> nest.EmployeeMessage
	0, // 1: nest.DepartmentMessage.parent_department:type_name -> nest.DepartmentMessage
	0, // 2: nest.DepartmentMessage.child_departments:type_name -> nest.DepartmentMessage
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_nest_proto_init() }
func file_nest_proto_init() {
	if File_nest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepartmentMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nest_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmployeeMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nest_proto_goTypes,
		DependencyIndexes: file_nest_proto_depIdxs,
		MessageInfos:      file_nest_proto_msgTypes,
	}.Build()
	File_nest_proto = out.File
	file_nest_proto_rawDesc = nil
	file_nest_proto_goTypes = nil
	file_nest_proto_depIdxs = nil
}
