mongodb:
  image: mongo:4.2
  restart: 'on-failure:3'
  container_name: dev-mongodb
  ports:
    - 27017:27017
  volumes:
    - /root/mongodb/logs:/var/log/mongodb
    - /root/mongodb/data/db/:/var/lib/mongodb
  command: mongod --auth
  environment:
    TZ: Asia/Shanghai
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

storj:
  image: erangaeb/storj:1.0
  container_name: storj
  environment:
    - MONGO_HOST=host.docker.internal
    - MONGO_PORT=27017
    - MONGO_DB=rahasak
    - MONGO_USER=rahasakadmin
    - MONGO_PASS=rahasakadmin
